class PolicyConfig:
    MAX_TEACHING_LOAD = 18
    MIN_TEACHING_LOAD = 12
    OFFICE_HOURS_RATIO = 0.5
    ALLOWED_DAYS = [["S","M","W"],["TH","T"]]
    MIN_TEACHING_DAYS = 4
    MAX_CONSECUTIVE = 2
    MERGED_ALLOWED = ALLOWED_DAYS[0] +ALLOWED_DAYS[1]

